name: images
description: A Dart library for image providers ( uploadcare, imgix ).
version: 1.0.0
homepage: https://github.com/amondnet/images.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
